-- No-op. Kept so version 7 stays in the sequence for databases that
-- already recorded it.
--
-- This migration originally created a global UNIQUE index on
-- `credentials(name)`. Credential names are not unique by design: vend by
-- name is Cedar-filtered and returns 300 Multiple Choices on ambiguity, and
-- 011 dropped the index for that reason. Left in place, this migration
-- failed at startup on any pre-007 database that already held two
-- credentials with the same name, which the product explicitly allows.
--
-- Fresh installs and upgrades from any version now pass straight through.
-- Databases that applied the original 007 still have the index dropped
-- by 011.
